### ISSUE TITLE
Upload is not working

### ISSUE THREAD

**Issue by cedx** [aquafadas-com/gulp-smartling#2]
When I try to upload some file, I always get this error :

```
throw new Error('Task 'name' requires a function that is a function');
^
Error: Task i18n:upload requires a function that is a function
at Gulp.Orchestrator.add (/Users/aymeric/Aquafadas-Videos/node_modules/orchestrator/index.js:44:10)
at Object.<anonymous> (/Users/aymeric/Aquafadas-Videos/gulpfile.js:109:6)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by cedx** [comment]
It's a regression: it will be fixed in the next release (v2.0.1).
